columns:
  Loan_ID: object
  Gender:  object
  Married: object
  Dependents: object
  Education: object
  Self_Employed: object
  ApplicantIncome: int64
  CoapplicantIncome: float64
  LoanAmount: float64
  Loan_Amount_Term: float64
  Credit_History: float64
  Property_Area: object
  Loan_Status: object

numerical_columns:
  - ApplicantIncome
  - CoapplicantIncome
  - LoanAmount
  - Loan_Amount_Term
  - Credit_History

category_columns:
  - Loan_ID
  - Gender
  - Married
  - Dependents
  - Education
  - Self_Employed
  - Property_Area
  - Loan_Status

drop_columns:
  - Loan_ID
  
target_columns:
  -Loan_status
